### ISSUE TITLE
Newbie here, I can't  seems to startup ur Monitoring part on my router

### ISSUE THREAD

**Issue by bendcat** [vortex-5/ddwrt-bwmon#18]
Hi,
I am using a router without USB port (no usb, direct from router) then I use Putty and follow your instruction, but I think I'm still missing something because I can't run your monitoring bwmon.html

I am new on DD-WRT and ssh. I need help, what am I missing. I hope you can help me thanks.

below is copy paste from Putty:
`BusyBox v1.24.1 (2016-02-19 10:26:55 CET) built-in shell (ash)

root@DD-WRT:~# cd /jffs/
root@DD-WRT:/jffs# wget https://github.com/vortex-5/ddwrt-bwmon/releases/downloa
d/1.6.2/bwmon.tar.gz
Connecting to github.com (192.30.252.129:443)
root@DD-WRT:/jffs# tar -xzvf bwmon.tar.gz

root@DD-WRT:/jffs# cd /jffs/bwmon/ && sh install.sh
-sh: cd: can't cd to /jffs/bwmon/

root@DD-WRT:/jffs# -o rw,unmask=0000 cd /jffs/bwmon/ && sh install.sh
-sh: -o: not found

root@DD-WRT:/jffs# chmod +x  cd /jffs/bwmon/ && sh install.sh
root@DD-WRT:/jffs#`

**Comment by vortex-5** [comment]
If you have no storage mounted to jffs you will not be able to extract to it.

**Comment by vortex-5** [comment]
JFFS only exists after you mounted USB storage to that folder.

you can try extracting to /tmp that's the ramdisk

just be warned the ramdisk dissappears once you reboot.

**Comment by bendcat** [comment]
Ok what i've done is this, please correct me if I'm wrong because I can't seem run the http://192.168.1.1:81/bwmon.html


`BusyBox v1.24.1 (2016-02-19 10:26:55 CET) built-in shell (ash)

root@DD-WRT:~# cd /tmp/
root@DD-WRT:/tmp# wget https://github.com/vortex-5/ddwrt-bwmon/releases/download
/1.6.2/bwmon.tar.gz
Connecting to github.com (192.30.252.129:443)
root@DD-WRT:/tmp# tar -xzvf bwmon.tar.gz
root@DD-WRT:/tmp# chmod +x cd /tmp/bwmon/ && sh install.sh
root@DD-WRT:/tmp# nvram /tmp/bwmon/startup.sh
root@DD-WRT:/tmp# nvram commit`

Please help me, Thanks.

**Comment by vortex-5** [comment]
you don't need to nvram set anything but as far as not beign able to run it you said on the ddwrt forums that you can't create the /tmp/bwmon folder so that's an obvious problem.

**Comment by bendcat** [comment]
I don't know what do you mean "that's obvious",
I tried using **mkdir bwmon** and it was successfully created.
What I tried is this after mkdir.
`BusyBox v1.24.1 (2016-02-19 10:26:55 CET) built-in shell (ash)

root@DD-WRT:~# ls -a
.     ..    .ssh
root@DD-WRT:~# cd tmp
-sh: cd: can't cd to tmp
root@DD-WRT:~# cd /tmp
root@DD-WRT:/tmp# ls -a
.                 cron.d            loginprompt       root
..                crontab           mnt               services
.ipt              dnsmasq.conf      nocat.leases      start_splashd.sh
.rule             dnsmasq.leases    nvram             udhcpc
.wanuptime        etc               oet               udhcpc.expires
TZ                hosts             resolv.conf       var
bwmon             igmpproxy.conf    resolv.dnsmasq    www
root@DD-WRT:/tmp# cd bwmon
root@DD-WRT:/tmp/bwmon# ls -a
.   ..
root@DD-WRT:/tmp/bwmon# cd ..
root@DD-WRT:/tmp# wget https://github.com/vortex-5/ddwrt-bwmon/releases/download
/1.6.2/bwmon.tar.gz
Connecting to github.com (192.30.252.128:443)
root@DD-WRT:/tmp# cd bwmon
root@DD-WRT:/tmp/bwmon# ls -a
.   ..
root@DD-WRT:/tmp/bwmon# cd ..
root@DD-WRT:/tmp# ls -a
.                 cron.d            loginprompt       root
..                crontab           mnt               services
.ipt              dnsmasq.conf      nocat.leases      start_splashd.sh
.rule             dnsmasq.leases    nvram             udhcpc
.wanuptime        etc               oet               udhcpc.expires
TZ                hosts             resolv.conf       var
bwmon             igmpproxy.conf    resolv.dnsmasq    www
root@DD-WRT:/tmp#
`

may be this command:
**tar -xzvf bwmon.tar.gz** doesn't create a bwmon folder or this files doesn't extract at all
I can't seem find the answer also on google, what I can think about is the command line doesn't extract or maybe something wrong in my commands in putty.

my router is Linksys E1200 v2 DD-WRT (K3)
I am really new into this things, I need help. Thanks.

**Comment by bendcat** [comment]
Solved using WinSCP
Problem is the putty it only execute ssh commands but it can't transfer files.

WinSCP ftw.

**Comment by vortex-5** [comment]
it says use putty to login to your router via ssh and execute wget.

When you execute wget you are asking the router to download the file by itself which you do not require file transfer capabilities of the host computer.

putty is fully capable of connecting via ssh and executing wget on the remote system there is no error in the instructions. 

It also says if you have problems you can download the file directly to your usb drive which bypasses the need of winSCP

I have highly recommended people not use the tool on a system that does not have removable storage because if the tool writes to system eeprom there are limited writes and you can burn out the built in flash epprom chip. Those instructions are not provided for this reason and should only be attempted by people that understand the risk which I expect to be more technical and willing to brick their router.

Suffice to say the only recommended usage is with a removable storage on your router OR over CIFS network share however that has it's own problems like reliability.

Again using the router's internal storage is not recommended and you may eventually brick your router.
