### ISSUE TITLE
BWMON

### ISSUE THREAD

**Issue by raybishop15** [vortex-5/ddwrt-bwmon#20]
Good morning, 

I was have been using the for a month now I love it! i was wondering if there is a way to keep your information after you restart the router thank you!

**Comment by vortex-5** [comment]
As long as you run it off of the USB drive it should retain information after reboot.

The save functions are executed every 15 min into the data directory.

if you do not have a bwmon/data directory that means you're using an older version that had a bug that is resolved in the latest version.

**Comment by raybishop15** [comment]
is that the version that is posted up 1.6.2

thanks!

**Comment by vortex-5** [comment]
1.6.2 yes https://github.com/vortex-5/ddwrt-bwmon/releases


I noted that there was a bugfix for not creating the data folder for certain users and thus not saving / persisting their logging data.

Keep in mind it only saves once every 15 min you can force the save by running bwmon-backup.sh but otherwise it does it every 15min to save on usb flash drive writes. There is a limited number of writes on flash media so I'm trying to prolong the life of these devices where possible.
