### ISSUE TITLE
Webpage not loading properly

### ISSUE THREAD

**Issue by pords** [vortex-5/ddwrt-bwmon#24]
usage.js gets updated but the frontend does not display properly.
i.e. 
<img width="1162" alt="screen shot 2016-03-17 at 2 53 45 am" src="https://cloud.githubusercontent.com/assets/328796/13825045/ba977cae-ebeb-11e5-9b8a-3dc803ee6478.png">

**Comment by vortex-5** [comment]
Try clearing your browser cache after you update.

And if that doesn't work take a screen shot of the console errors. (F12)

**Comment by pords** [comment]
Still doesn't work.

<img width="1065" alt="screen shot 2016-03-17 at 1 17 47 pm" src="https://cloud.githubusercontent.com/assets/328796/13837103/c53bc37a-ec42-11e5-88bb-b09840c40d2f.png">

**Comment by vortex-5** [comment]
It looks like it does not work because it can't access the file /tmp/www/ui-bootstrap-tpls.min.js

this file shows up with http://rouiterIp/user/ui-bootstrap-tpls.min.js

did you change the bwmon.html file? 

as you can see https://github.com/vortex-5/ddwrt-bwmon/blob/master/bwmon/www/bwmon.html#L8 the file uses relative path.

You need to access your UI as follows

http://192.168.1.1/user/bwmon.html

or what ever your router IP is.

if you changed it to a DNS entry like with openDNS it won't be able to find the resources.

**Comment by pords** [comment]
I see. Thank you. Oddly, there is no ui-bootstrap-tpls.min.js in tmp/www/ nor in /jffs/bwmon/www.

**Comment by vortex-5** [comment]
Ok maybe it didn't extract properly?
