### ISSUE TITLE
Display IP & MAC?

### ISSUE THREAD

**Issue by SeaWolf-666** [vortex-5/ddwrt-bwmon#25]
Hello,
Love the scripts, it has been really helpful. I am wondering if it is possible for the page to also display the IP address connected to the MAC address. I have to arp the MAC every time I need to check, or look in the dd-wrt interface. I was hoping to get all that data in one place. I have some coding experience maybe I could modify it myself? Any suggestions?

Thank agin,
-SeaWolf

**Comment by vortex-5** [comment]
Currently what we have
if you go to DDWRT services and assign static ip's if you do that then it should automatically figure out the host name from it in the current version I have up.

if you want to assign names to the mac-names.js it will override and use these names for the mac addresses

Future planned changes:

(currently on client-side-dns branch work is in progress but slow since there's a bit of complexity re-writing how the entire dns subsystem works)

the usage.js files do not track IP's since they are unreliable if the host changes ip address since we are tracking devices.

What I'm working on in the new version is I want to symlink the two dns files into /tmp/www for the non lighttpd users and include it as part of bwreader.php this way we can have the dns names ip addresses and mac names available to the front end JS scripts and they will handle processing and matching up this information. Additionally this should allow even the people running the non-lighttpd version to get instant updates to the dns leases while they are on the page.

However because the undertaking is a semi larger re-write I'll probably do this once I have more a block of free time so I can properly test this.

**Comment by vortex-5** [comment]
if you want to edit this yourself I'm planning on changing:

the get data routines inside of bwmon.js

the bwmon.html file to include these extra sections in the tool tip

start.sh to most likely conditionally create the sym links (only if you are not running lighttpd)

stop.sh to remove the sym links on close

bwreader.php to include the additional section for the dns (this is already done on the branch).

I've already planned to make this improvement so most likely we're looking at next month I will probably have something written and tested. If you want to try yourself you can fork the repository to make these edits. Keep in mind any pull requests will go through code review to ensure that the styles match up before they are merged back into the main code base.

Pull requests will be rejected if there is a lot of additional service code since the focus for this project is to remain lightweight in terms of router processing overhead.

That said you always have your fork at that point which is the beauty of open source.

**Comment by vortex-5** [comment]
Version 1.7.0 is up it covers this you can now see the IP and MAC in the tooltip.

You can also toggle the buttons at the bottom to switch to IP mode and MAC mode should you not want to see the resolved names.
