### ISSUE TITLE
Not logging clients using Privoxy

### ISSUE THREAD

**Issue by oubcat96** [vortex-5/ddwrt-bwmon#61]
So I decided to leverage the Ad Blocking feature in ddwrt (Privoxy) and it looks like the bandwidth monitor is no longer logging the traffic of those clients using the proxy. Is this expected? The clients are pointing to the router ip and port 8118.

**Comment by vortex-5** [comment]
Hmm... that one is tricky when you utilize the proxy none of the clients are actually being routed through the router.

Instead they contact the proxy and all traffic shows up as going through the router.

Since we don't count lan traffic the router's lan IP would count as lan traffic and that's why it wouldn't show up.

Also we can't count the router's traffic because that would be the same as wan traffic.

If you think of the router as a dam it can only measure things passing through the dam a proxy means packets aren't leaving the dam instead they are given to the border control guard and they recieve shipments but the packets never actually pass through so they aren't counted.
