### ISSUE TITLE
Underreports bandwidth usage on a Netgear R7000 running kongac

### ISSUE THREAD

**Issue by BabyPuncher** [vortex-5/ddwrt-bwmon#67]
It appears to be function as expected, however the bandwidth tallies do not seem to go up much when making large downloads. For example, downloading a 20 GB game off Steam resulted in that machine reporting only 5 MB bandwidth used in bwmon. The total bandwidth also does not reflect this usage.

**Comment by vortex-5** [comment]
Some people have reported problems with SFE when enabled as it bypasses the firewall rules which are used to do the data tallies.

**Comment by BabyPuncher** [comment]
Hmmm, it looks like I already have shortcut forwarding engine disabled. I'm begging to suspect only my desktop is affected, the number from other devices on my network (both wireless and wired) look reasonable.

**Comment by vortex-5** [comment]
In simple terms due to how DDWRT is structured it can only count rules going through a firewall layer. how DDWRT works is it adds a firewall chain (a layer if you will) on top of the normal firewall as full pass through for the sole purpose of counting packets. If the traffic you are talking about is bypassing the firewall entirely I.E. DMZ or LAN traffic it would not be counted in the final stats as it's invisible to BWMON.

**Comment by BabyPuncher** [comment]
Does bwmon capture IPV6 traffic or only IPV4?

**Comment by vortex-5** [comment]
Our ISP's over here don't use IPv6 so I have no way of testing if IPv6 is working.
